// The rebuild package's single write guard, emitted as a real script at
// .claude/hooks/rebuild-guard.mjs instead of inline `node -e` strings.
//
// Why a file: inline commands are rewritten by the shell before node sees
// them, which is how the original untested-contracts hook shipped with a
// regex the shell mangled into a SyntaxError (exit 1, a non-blocking hook
// error) on every call. A file is executed byte-for-byte.
//
// Why this much logic: guard probes and a live challenge against the
// previous hooks (ablation/review-2026-09/) got protected writes through a
// case variant (`Spec/` on case-insensitive APFS), a symlink alias, shell
// commands (`echo >`, python one-liners, `mv`), and a malformed blocklist
// (the hooks failed open). This script closes each of those:
//   - every target is resolved against the session cwd, symlinks in its
//     existing ancestors are followed, and comparison is case-insensitive on
//     macOS/Windows;
//   - Bash commands are parsed for write-shaped constructs (redirects, tee,
//     sed -i, rm/mv/cp/ln/touch and friends, git write subcommands,
//     interpreter one-liners that write), with `cd` tracked across chained
//     statements; pure reads (`cat spec/...`, `rg ... spec/`) stay allowed;
//   - an unreadable blocklist or payload blocks instead of allowing;
//   - the guard protects itself: .claude/settings.json and .claude/hooks/
//     are locked like spec/.
// Known limit, stated in the paper: shell parsing is heuristic. A write
// hidden behind indirection it cannot see (a script file the agent wrote
// earlier, eval of a computed string) is not caught.
//
// The source below must contain no backticks and no dollar-brace sequence,
// so it can live verbatim inside String.raw.
export const GUARD_HOOK_RELATIVE_PATH = '.claude/hooks/rebuild-guard.mjs';

export const GUARD_HOOK_SOURCE = String.raw`#!/usr/bin/env node
// rebuild-dossier write guard (generated by generate_spec; do not edit).
import { readFileSync, existsSync, realpathSync } from 'node:fs';
import { resolve, dirname, basename, join, sep } from 'node:path';

const FOLD = process.platform === 'darwin' || process.platform === 'win32';
const UNTESTED_MSG = 'this file corresponds to a locked contract with no associated test in tests/visible/ yet. ' +
  'Building it now is batch regeneration, which this workspace disallows -- work test-by-test. ' +
  'If this file genuinely must be built ahead of a failing test, stop and ask first.';

function block(msg) {
  process.stderr.write('Blocked: ' + msg + '\n');
  process.exit(2);
}

function canonical(p, base) {
  let abs = resolve(base, String(p).split(String.fromCharCode(92)).join('/'));
  const tail = [];
  let head = abs;
  while (!existsSync(head)) {
    const parent = dirname(head);
    if (parent === head) break;
    tail.unshift(basename(head));
    head = parent;
  }
  let real = head;
  try { real = realpathSync(head); } catch (e) { real = head; }
  abs = tail.length ? join(real, ...tail) : real;
  return FOLD ? abs.toLowerCase() : abs;
}

function within(p, dir) {
  return p === dir || p.startsWith(dir + sep);
}

function shellSplit(s) {
  const out = [];
  let cur = '';
  let quote = null;
  let any = false;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (quote) {
      if (c === quote) quote = null;
      else if (c === String.fromCharCode(92) && quote === '"' && i + 1 < s.length) cur += s[++i];
      else cur += c;
      continue;
    }
    if (c === '"' || c === "'") { quote = c; any = true; continue; }
    if (c === String.fromCharCode(92) && i + 1 < s.length) { cur += s[++i]; any = true; continue; }
    if (/\s/.test(c)) { if (any || cur) out.push(cur); cur = ''; any = false; continue; }
    cur += c;
  }
  if (any || cur) out.push(cur);
  return out;
}

const ALL_ARGS = new Set(['rm', 'rmdir', 'unlink', 'mv', 'touch', 'truncate', 'chmod', 'chown', 'ln', 'mkdir', 'tee', 'shred']);
const LAST_ARG = new Set(['cp', 'install', 'rsync']);
const INTERPRETERS = new Set(['python', 'python3', 'node', 'perl', 'ruby', 'deno', 'bun', 'php']);
const GIT_WRITES = new Set(['rm', 'mv', 'checkout', 'restore', 'apply', 'stash', 'reset', 'clean']);
const WRITEISH = /open\([^)]*['"][wax+]|writeFile|write_text|write_bytes|appendFile|unlink|rename|remove|rmSync|rmdir|shutil\.|os\.system|copyFile|symlink|truncate|>/;

function bashTargets(command, cwd) {
  const found = [];
  let dir = cwd;
  for (const stmt of command.split(/&&|\|\||;|\||\n/)) {
    for (const m of stmt.matchAll(/>{1,2}\s*("[^"]*"|'[^']*'|[^\s;&|<>]+)/g)) {
      const t = m[1].replace(/^['"]|['"]$/g, '');
      if (t && !t.startsWith('&')) found.push([t, dir]);
    }
    const words = shellSplit(stmt.replace(/\d?>{1,2}\s*("[^"]*"|'[^']*'|[^\s;&|<>]+)/g, ' '));
    let i = 0;
    while (i < words.length && (/^[A-Za-z_][A-Za-z0-9_]*=/.test(words[i]) || words[i] === 'sudo' || words[i] === 'command')) i++;
    if (i >= words.length) continue;
    const name = basename(words[i]);
    const args = words.slice(i + 1);
    const plain = args.filter((a) => !a.startsWith('-'));
    if (name === 'cd') { if (plain[0]) dir = resolve(dir, plain[0]); continue; }
    if (ALL_ARGS.has(name)) plain.forEach((a) => found.push([a, dir]));
    else if (LAST_ARG.has(name)) {
      const t = args.indexOf('-t');
      if (t >= 0 && args[t + 1]) found.push([args[t + 1], dir]);
      else if (plain.length) found.push([plain[plain.length - 1], dir]);
    } else if (name === 'sed' && args.some((a) => /^-[a-zA-Z]*i/.test(a) || a.startsWith('--in-place'))) {
      plain.forEach((a) => found.push([a, dir]));
    } else if (name === 'dd') {
      args.filter((a) => a.startsWith('of=')).forEach((a) => found.push([a.slice(3), dir]));
    } else if (name === 'git' && GIT_WRITES.has(plain[0])) {
      plain.slice(1).forEach((a) => found.push([a, dir]));
    } else if (INTERPRETERS.has(name.replace(/[0-9.]+$/, '') ) || INTERPRETERS.has(name)) {
      const code = args.join(' ');
      if (WRITEISH.test(code)) {
        for (const lit of code.matchAll(/'([^']+)'|"([^"]+)"/g)) found.push([lit[1] || lit[2], dir]);
        for (const tok of code.split(/[\s(),]+/)) if (tok.includes('/')) found.push([tok.replace(/['"]/g, ''), dir]);
      }
    }
  }
  return found;
}

let raw = '';
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  let j;
  try { j = JSON.parse(raw); } catch (e) { block('the hook payload could not be parsed, so this write cannot be checked.'); }
  const cwd = j.cwd || process.cwd();
  const specDir = canonical('spec', cwd);
  const settings = canonical('.claude/settings.json', cwd);
  const hooksDir = canonical('.claude/hooks', cwd);
  let untested = [];
  const listPath = join(cwd, 'spec', 'untested-contracts.json');
  if (existsSync(listPath)) {
    try {
      const list = JSON.parse(readFileSync(listPath, 'utf-8'));
      if (!Array.isArray(list)) throw new Error('not an array');
      untested = list.map((u) => canonical(String(u), cwd));
    } catch (e) {
      block('spec/untested-contracts.json is unreadable, so untested-contract protection cannot be checked; restore it before building.');
    }
  }
  const reason = (p) => {
    if (within(p, specDir)) return 'spec/ is locked — do not edit files under spec/.';
    if (p === settings || within(p, hooksDir)) return 'the workspace guard and its settings are locked.';
    if (untested.includes(p)) return UNTESTED_MSG;
    return null;
  };
  const input = j.tool_input || {};
  const targets = [];
  if (j.tool_name === 'Bash') targets.push(...bashTargets(String(input.command || ''), cwd));
  else for (const k of ['file_path', 'notebook_path', 'path']) if (typeof input[k] === 'string') targets.push([input[k], cwd]);
  for (const [t, base] of targets) {
    for (const variant of [t, t.replace(/\\(.)/g, '$1')]) {
      const why = reason(canonical(variant, base));
      if (why) block(why);
    }
  }
  process.exit(0);
});
`;
